;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        apply-operation-to-number-at-point
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        c-indent-line-or-region
        comment-dwim-line
        completion-at-point
        easy-kill
        electric-newline-and-maybe-indent
        kill-region
        prelude-eval-and-replace
        sp-backward-delete-char
        sp-backward-kill-word
        sp-delete-char
        sp-forward-sexp
        sp-kill-word
        sp-splice-sexp
        ))

(setq mc/cmds-to-run-once
      '(
        god-local-mode
        yank-rectangle
        ))
